// <auto-generated />
using System;
using DoAnCoSo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnCoSo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnCoSo.Models.ChatHistory", b =>
                {
                    b.Property<int>("MaChatHistory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChatHistory"));

                    b.Property<string>("BotResponse")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContextData")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Intent")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MessageType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaChatHistory");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("ChatHistory");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ChiSoDien", b =>
                {
                    b.Property<int>("MaDien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDien"));

                    b.Property<string>("HinhAnhDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaGiaDien")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThangDien")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoDienCu")
                        .HasColumnType("int");

                    b.Property<int>("SoDienMoi")
                        .HasColumnType("int");

                    b.Property<int>("SoDienTieuThu")
                        .HasColumnType("int");

                    b.Property<decimal>("TienDien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaDien");

                    b.HasIndex("MaGiaDien");

                    b.HasIndex("MaPhong");

                    b.ToTable("ChiSoDien");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ChiSoNuoc", b =>
                {
                    b.Property<int>("MaNuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNuoc"));

                    b.Property<string>("HinhAnhNuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaGiaNuoc")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThangNuoc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoNuocCu")
                        .HasColumnType("int");

                    b.Property<int>("SoNuocMoi")
                        .HasColumnType("int");

                    b.Property<int>("SoNuocTieuThu")
                        .HasColumnType("int");

                    b.Property<decimal>("TienNuoc")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaNuoc");

                    b.HasIndex("MaGiaNuoc");

                    b.HasIndex("MaPhong");

                    b.ToTable("ChiSoNuoc");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaDichVu");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("ChiTietHoaDon");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ChiTietHopDong", b =>
                {
                    b.Property<int>("MaChiTietHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietHopDong"));

                    b.Property<int>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiThue")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietHopDong");

                    b.HasIndex("MaHopDong");

                    b.HasIndex("MaNguoiThue");

                    b.ToTable("ChiTietHopDong");
                });

            modelBuilder.Entity("DoAnCoSo.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Tiendichvu")
                        .HasColumnType("real");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("DoAnCoSo.Models.GiaDien", b =>
                {
                    b.Property<int>("MaGiaDien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaDien"));

                    b.Property<int>("BacDien")
                        .HasColumnType("int");

                    b.Property<int>("DenSoDien")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaTienDien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TuSoDien")
                        .HasColumnType("int");

                    b.HasKey("MaGiaDien");

                    b.HasIndex("BacDien")
                        .IsUnique();

                    b.ToTable("GiaDien");
                });

            modelBuilder.Entity("DoAnCoSo.Models.GiaNuoc", b =>
                {
                    b.Property<int>("MaGiaNuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaNuoc"));

                    b.Property<int>("BacNuoc")
                        .HasColumnType("int");

                    b.Property<int>("DenSoNuoc")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaTienNuoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TuSoNuoc")
                        .HasColumnType("int");

                    b.HasKey("MaGiaNuoc");

                    b.HasIndex("BacNuoc")
                        .IsUnique();

                    b.ToTable("GiaNuoc");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<string>("KyHoaDon")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("MaDien")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiThue")
                        .HasColumnType("int");

                    b.Property<int>("MaNuoc")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienDichVu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaDien");

                    b.HasIndex("MaNguoiThue");

                    b.HasIndex("MaNuoc");

                    b.HasIndex("MaPhong");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HopDong", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHopDong"));

                    b.Property<int>("MaNguoiThue")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaNguoiThue");

                    b.HasIndex("MaPhong");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("DoAnCoSo.Models.LichSuDongMo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<string>("NguoiThucHien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaPhong");

                    b.ToTable("LichSuDongMo");
                });

            modelBuilder.Entity("DoAnCoSo.Models.LichSuGiaDichVu", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<decimal>("GiaDichVu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaDichVu");

                    b.ToTable("LichSuGiaDichVu");
                });

            modelBuilder.Entity("DoAnCoSo.Models.LoaiPhong", b =>
                {
                    b.Property<int>("MaLoaiPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiPhong"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiPhong");

                    b.ToTable("LoaiPhong");
                });

            modelBuilder.Entity("DoAnCoSo.Models.NguoiThue", b =>
                {
                    b.Property<int>("MaNguoiThue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiThue"));

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiCongTac")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuocTich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaNguoiThue");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique()
                        .HasFilter("[MaNguoiDung] IS NOT NULL");

                    b.ToTable("NguoiThue");
                });

            modelBuilder.Entity("DoAnCoSo.Models.NhaTro", b =>
                {
                    b.Property<int>("MaNhaTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaTro"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenNhaTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNhaTro");

                    b.ToTable("NhaTro");
                });

            modelBuilder.Entity("DoAnCoSo.Models.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<float?>("DienTich")
                        .HasColumnType("real");

                    b.Property<decimal>("GiaPhong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaNhaTro")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaLoaiPhong");

                    b.HasIndex("MaNhaTro");

                    b.ToTable("Phong");
                });

            modelBuilder.Entity("DoAnCoSo.Models.SuCo", b =>
                {
                    b.Property<int>("MaSuCo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSuCo"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNguoiThue")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBaoCao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSuCo");

                    b.HasIndex("MaNguoiThue");

                    b.HasIndex("MaPhong");

                    b.ToTable("SuCo");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiThue")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaNguoiThue");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("DoAnCoSo.Models.TinNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DaDocAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DaSua")
                        .HasColumnType("bit");

                    b.Property<bool>("DaThuHoi")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiNguoiGui")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoaiNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaNguoiGui")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiNhan")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungGoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianGui")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TinNhan");
                });

            modelBuilder.Entity("DoAnCoSo.Models.User", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ChatHistory", b =>
                {
                    b.HasOne("DoAnCoSo.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ChiSoDien", b =>
                {
                    b.HasOne("DoAnCoSo.Models.GiaDien", "GiaDien")
                        .WithMany()
                        .HasForeignKey("MaGiaDien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GiaDien");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ChiSoNuoc", b =>
                {
                    b.HasOne("DoAnCoSo.Models.GiaNuoc", "GiaNuoc")
                        .WithMany()
                        .HasForeignKey("MaGiaNuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GiaNuoc");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("DoAnCoSo.Models.DichVu", "DichVu")
                        .WithMany("ChiTietHoaDon")
                        .HasForeignKey("MaDichVu");

                    b.HasOne("DoAnCoSo.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDon")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ChiTietHopDong", b =>
                {
                    b.HasOne("DoAnCoSo.Models.HopDong", "HopDong")
                        .WithMany()
                        .HasForeignKey("MaHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.NguoiThue", "NguoiThue")
                        .WithMany()
                        .HasForeignKey("MaNguoiThue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("NguoiThue");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HoaDon", b =>
                {
                    b.HasOne("DoAnCoSo.Models.ChiSoDien", "ChiSoDien")
                        .WithMany()
                        .HasForeignKey("MaDien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.NguoiThue", "NguoiThue")
                        .WithMany()
                        .HasForeignKey("MaNguoiThue")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.ChiSoNuoc", "ChiSoNuoc")
                        .WithMany()
                        .HasForeignKey("MaNuoc")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChiSoDien");

                    b.Navigation("ChiSoNuoc");

                    b.Navigation("NguoiThue");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HopDong", b =>
                {
                    b.HasOne("DoAnCoSo.Models.NguoiThue", "NguoiThue")
                        .WithMany()
                        .HasForeignKey("MaNguoiThue")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiThue");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAnCoSo.Models.LichSuDongMo", b =>
                {
                    b.HasOne("DoAnCoSo.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAnCoSo.Models.LichSuGiaDichVu", b =>
                {
                    b.HasOne("DoAnCoSo.Models.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("DoAnCoSo.Models.NguoiThue", b =>
                {
                    b.HasOne("DoAnCoSo.Models.User", "User")
                        .WithOne("NguoiThue")
                        .HasForeignKey("DoAnCoSo.Models.NguoiThue", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAnCoSo.Models.Phong", b =>
                {
                    b.HasOne("DoAnCoSo.Models.LoaiPhong", "LoaiPhong")
                        .WithMany()
                        .HasForeignKey("MaLoaiPhong")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.NhaTro", "NhaTro")
                        .WithMany()
                        .HasForeignKey("MaNhaTro")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LoaiPhong");

                    b.Navigation("NhaTro");
                });

            modelBuilder.Entity("DoAnCoSo.Models.SuCo", b =>
                {
                    b.HasOne("DoAnCoSo.Models.NguoiThue", "NguoiThue")
                        .WithMany()
                        .HasForeignKey("MaNguoiThue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiThue");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ThanhToan", b =>
                {
                    b.HasOne("DoAnCoSo.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.NguoiThue", "NguoiThue")
                        .WithMany()
                        .HasForeignKey("MaNguoiThue")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("NguoiThue");
                });

            modelBuilder.Entity("DoAnCoSo.Models.DichVu", b =>
                {
                    b.Navigation("ChiTietHoaDon");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDon");
                });

            modelBuilder.Entity("DoAnCoSo.Models.User", b =>
                {
                    b.Navigation("NguoiThue");
                });
#pragma warning restore 612, 618
        }
    }
}
